"""add deleted_for to chat_messages

Revision ID: 1c5150df2092
Revises: ba2f2f9df5c9
Create Date: 2026-09-24 18:34:40.617314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c5150df2092'
down_revision: Union[str, None] = 'ba2f2f9df5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('deleted_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'deleted_for')
    # ### end Alembic commands ###
