"""add bee tasks, checkpoints, permissions

Revision ID: 359ecdb76af3
Revises: 5def6414560b
Create Date: 2026-09-18 18:55:32.758545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359ecdb76af3'
down_revision: Union[str, None] = '5def6414560b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bee_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('bee_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_dna', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('stoppable', sa.Boolean(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['bee_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_tasks_bee_type'), 'bee_tasks', ['bee_type'], unique=False)
    op.create_index(op.f('ix_bee_tasks_status'), 'bee_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_bee_tasks_user_id'), 'bee_tasks', ['user_id'], unique=False)
    op.create_table('bee_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['bee_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_checkpoints_task_id'), 'bee_checkpoints', ['task_id'], unique=False)
    op.create_index(op.f('ix_bee_checkpoints_user_id'), 'bee_checkpoints', ['user_id'], unique=False)
    op.create_table('bee_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['bee_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_permissions_user_id'), 'bee_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bee_permissions_user_id'), table_name='bee_permissions')
    op.drop_table('bee_permissions')
    op.drop_index(op.f('ix_bee_checkpoints_user_id'), table_name='bee_checkpoints')
    op.drop_index(op.f('ix_bee_checkpoints_task_id'), table_name='bee_checkpoints')
    op.drop_table('bee_checkpoints')
    op.drop_index(op.f('ix_bee_tasks_user_id'), table_name='bee_tasks')
    op.drop_index(op.f('ix_bee_tasks_status'), table_name='bee_tasks')
    op.drop_index(op.f('ix_bee_tasks_bee_type'), table_name='bee_tasks')
    op.drop_table('bee_tasks')
    # ### end Alembic commands ###
