"""add last_decay_at to users

Revision ID: 438fd5b25d17
Revises: 849e36585797
Create Date: 2026-09-16 19:22:34.055250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438fd5b25d17'
down_revision: Union[str, None] = '849e36585797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_decay_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_decay_at')
    # ### end Alembic commands ###
