"""add memory usage tracking

Revision ID: 849e36585797
Revises: f810a7bcee49
Create Date: 2026-09-16 19:08:02.880023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849e36585797'
down_revision: Union[str, None] = 'f810a7bcee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('use_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('memories', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'last_used_at')
    op.drop_column('memories', 'use_count')
    # ### end Alembic commands ###
