"""add condition column to automations

Revision ID: 8b8ab3510d71
Revises: fddbfe0a6f39
Create Date: 2026-09-17 19:54:11.101521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8ab3510d71'
down_revision: Union[str, None] = 'fddbfe0a6f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'condition')
    # ### end Alembic commands ###
