"""add chat blocks

Revision ID: 8d6b72e3d67b
Revises: 1c5150df2092
Create Date: 2026-09-24 18:42:33.214462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6b72e3d67b'
down_revision: Union[str, None] = '1c5150df2092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_chat_block')
    )
    op.create_index(op.f('ix_chat_blocks_blocked_id'), 'chat_blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_chat_blocks_blocker_id'), 'chat_blocks', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_blocks_blocker_id'), table_name='chat_blocks')
    op.drop_index(op.f('ix_chat_blocks_blocked_id'), table_name='chat_blocks')
    op.drop_table('chat_blocks')
    # ### end Alembic commands ###
