"""add pinned_at to chat_messages

Revision ID: ba2f2f9df5c9
Revises: c9a6ba989ddd
Create Date: 2026-09-24 10:02:27.022448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2f2f9df5c9'
down_revision: Union[str, None] = 'c9a6ba989ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_messages_pinned_at'), 'chat_messages', ['pinned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_pinned_at'), table_name='chat_messages')
    op.drop_column('chat_messages', 'pinned_at')
    # ### end Alembic commands ###
