"""add automations table

Revision ID: cce52d5b5f65
Revises: 438fd5b25d17
Create Date: 2026-09-17 18:11:41.414283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce52d5b5f65'
down_revision: Union[str, None] = '438fd5b25d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=5), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('task_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automations_enabled'), 'automations', ['enabled'], unique=False)
    op.create_index(op.f('ix_automations_next_run_at'), 'automations', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automations_user_id'), 'automations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automations_user_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_next_run_at'), table_name='automations')
    op.drop_index(op.f('ix_automations_enabled'), table_name='automations')
    op.drop_table('automations')
    # ### end Alembic commands ###
