"""add emergency stop to users

Revision ID: d39f023cac2c
Revises: 88c6d487e474
Create Date: 2026-09-17 21:01:44.552800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39f023cac2c'
down_revision: Union[str, None] = '88c6d487e474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_stop', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('emergency_stop_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('emergency_stop_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_stop_at')
    op.drop_column('users', 'emergency_stop_reason')
    op.drop_column('users', 'emergency_stop')
    # ### end Alembic commands ###
