"""add generated_videos

Revision ID: db1c3f5270d5
Revises: 359ecdb76af3
Create Date: 2026-09-20 11:03:50.089745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1c3f5270d5'
down_revision: Union[str, None] = '359ecdb76af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enhanced_prompt', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_videos_provider_task_id'), 'generated_videos', ['provider_task_id'], unique=False)
    op.create_index(op.f('ix_generated_videos_status'), 'generated_videos', ['status'], unique=False)
    op.create_index(op.f('ix_generated_videos_user_id'), 'generated_videos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_videos_user_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_status'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_provider_task_id'), table_name='generated_videos')
    op.drop_table('generated_videos')
    # ### end Alembic commands ###
