"""add pinned_at to chat_messages

Revision ID: db1e5e70aeaa
Revises: 8d6b72e3d67b
Create Date: 2026-09-24 20:30:19.769472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e5e70aeaa'
down_revision: Union[str, None] = '8d6b72e3d67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chats_pinned_at'), 'chats', ['pinned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_pinned_at'), table_name='chats')
    op.drop_column('chats', 'pinned_at')
    # ### end Alembic commands ###
