"""add learn tables

Revision ID: e112d63d712c
Revises: d1d569384dfe
Create Date: 2026-09-21 14:04:55.464131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e112d63d712c'
down_revision: Union[str, None] = 'd1d569384dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_preview', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learn_sessions_user_created', 'learn_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_learn_sessions_user_id'), 'learn_sessions', ['user_id'], unique=False)
    op.create_table('learn_flashcards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learn_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learn_flashcards_session_id'), 'learn_flashcards', ['session_id'], unique=False)
    op.create_table('learn_quiz_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learn_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learn_quiz_attempts_session_id'), 'learn_quiz_attempts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learn_quiz_attempts_session_id'), table_name='learn_quiz_attempts')
    op.drop_table('learn_quiz_attempts')
    op.drop_index(op.f('ix_learn_flashcards_session_id'), table_name='learn_flashcards')
    op.drop_table('learn_flashcards')
    op.drop_index(op.f('ix_learn_sessions_user_id'), table_name='learn_sessions')
    op.drop_index('ix_learn_sessions_user_created', table_name='learn_sessions')
    op.drop_table('learn_sessions')
    # ### end Alembic commands ###
